### ISSUE TITLE
Issue about error: AttributeError: 'module' object has no attribute 'hungarian'

### ISSUE THREAD

**Issue by huzhenzhen** [Russell91/TensorBox#13]
Hi,

I'm having an issue about hungarian layer.
I followed the steps of ReInspect Installation & Training, copy the hungarian code and make.
But when I trained the model, there is error:

> 
  File "train.py", line 359, in <module>
    main()
  File "train.py", line 356, in main
    train(H, test_images=[])
  File "train.py", line 251, in train
    smooth_op, global_step, learning_rate) = build(H, q)
  File "train.py", line 168, in build
    boxes_loss[phase]) = build_lstm(H, x, googlenet, phase, boxes, flags)
  File "train.py", line 83, in build_lstm
    tf.user_ops.hungarian(pred_boxes, outer_boxes, outer_flags))
AttributeError: 'module' object has no attribute 'hungarian'

I'm on tensorflow 0.7.1. python2.7

**Comment by Russell91** [comment]
I see. There is probably an issue with compiling or importing the wrong tensorflow. Can you try to follow the official tutorial on adding an op [here](https://www.tensorflow.org/versions/r0.7/how_tos/adding_an_op/index.html), and if you are able to add the zero_out op described there, the hungarian op should work fine. Please let me know otherwise. If you aren't able to add that op, it is possible that tensorflow has a bug in your version.

**Comment by huzhenzhen** [comment]
I reinstall the Tensorflow and the problem has been fixed.

Thank you very much!
