### ISSUE TITLE
Consider submitting Hungarian algorithm?

### ISSUE THREAD

**Issue by rueberger** [Russell91/TensorBox#47]
Would you consider submitting your implementation of the Hungarian algorithm to tf.contrib? A well-documented and community maintained implementation would be most welcome!

Thanks,
Andrew

**Comment by Russell91** [comment]
Sounds like a great idea. There would be a bit of work to it though. What's the best way to get started?

**Comment by rueberger** [comment]
Not sure, I'll file an issue asking what would be required. I'd definitely be willing to help get this contributed.

**Comment by Russell91** [comment]
Okay, do you have a pointer to the issue? The only real problem is that I don't have full ownership over the hungarian lib code itself, to license it as Google Apache code. So that would need to be rewritten, but perhaps google has an internal hungarian implementation that could be used? One could always spend an afternoon writing up something off of wikipedia from scratch as well.

**Comment by Russell91** [comment]
Okay, I've updated the readme to use an easier install strategy.
