### ISSUE TITLE
Error python train.py

### ISSUE THREAD

**Issue by pribadihcr** [Russell91/TensorBox#8]
Hi,

I run the demo:
~/TensorBox$ python train.py --hypes hypes/default.json --gpu 0 --logdir output

And got the following error:

I tensorflow/core/common_runtime/local_device.cc:25] Local device intra op parallelism threads: 8
I tensorflow/core/common_runtime/local_session.cc:45] Local session inter op parallelism threads: 8
Traceback (most recent call last):
  File "train.py", line 359, in <module>
    main()
  File "train.py", line 356, in main
    train(H, test_images=[])
  File "train.py", line 262, in train
    log_image = tf.image_summary(log_image_name, tf.expand_dims(test_image_to_log, 0))
  File "~/.local/lib/python2.7/site-packages/tensorflow/python/ops/summary_ops.py", line 89, in image_summary
    tag=tag, tensor=tensor, max_images=max_images, name=scope)
  File "~/.local/lib/python2.7/site-packages/tensorflow/python/ops/gen_summary_ops.py", line 90, in _image_summary
    name=name)
  File "~/.local/lib/python2.7/site-packages/tensorflow/python/ops/op_def_library.py", line 405, in apply_op
    (prefix, types_lib.as_dtype(input_arg.type).name))
TypeError: Input 'tensor' of 'ImageSummary' Op has type uint8 that does not match expected type of float32.

many thanks for help

**Comment by Russell91** [comment]
tf.image_summary is supposed to take a uint8 or a float32 (see docs below). You could try calling tf.to_float on the tensor first, or just commenting out that line. Can you confirm that you are using a recent version of Tensorflow?

Signature: tf.image_summary(tag, tensor, max_images=3, collections=None, name=None)
Docstring:
Outputs a `Summary` protocol buffer with images.

The summary has up to `max_images` summary values containing images. The
images are built from `tensor` which must be 4-D with shape `[batch_size,
height, width, channels]` and where `channels` can be:

*  1: `tensor` is interpreted as Grayscale.
*  3: `tensor` is interpreted as RGB.
*  4: `tensor` is interpreted as RGBA.

The images have the same number of channels as the input tensor. For float
input, the values are normalized one image at a time to fit in the range
`[0, 255]`.  `uint8` values are unchanged.  The op uses two different
normalization algorithms:

*  If the input values are all positive, they are rescaled so the largest one
   is 255.

*  If any input value is negative, the values are shifted so input value 0.0
   is at 127.  They are then rescaled so that either the smallest value is 0,
   or the largest one is 255.

The `tag` argument is a scalar `Tensor` of type `string`.  It is used to
build the `tag` of the summary values:

*  If `max_images` is 1, the summary value tag is '*tag*/image'.
*  If `max_images` is greater than 1, the summary value tags are
   generated sequentially as '*tag*/image/0', '*tag*/image/1', etc.

Args:
  tag: A scalar `Tensor` of type `string`. Used to build the `tag`
    of the summary values.
  tensor: A 4-D `uint8` or `float32` `Tensor` of shape `[batch_size, height,
    width, channels]` where `channels` is 1, 3, or 4.
  max_images: Max number of batch elements to generate images for.
  collections: Optional list of ops.GraphKeys.  The collections to add the
    summary to.  Defaults to [ops.GraphKeys.SUMMARIES]
  name: A name for the operation (optional).

Returns:
  A scalar `Tensor` of type `string`. The serialized `Summary` protocol
  buffer.
File:      ~/anaconda/lib/python2.7/site-packages/tensorflow/python/ops/summary_ops.py
Type:      function

**Comment by Russell91** [comment]
Please make sure you are using Tensorflow 0.7 or later. If this issue persists, or reoccurs, let me know!
